name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu VM provided by GitHub

    steps:
    - name: Checkout repository 
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Install Node.js
      uses: actions/setup-node@v2  # Set up Node.js environment
      with:
        node-version: '20'  # Specify the Node.js version to install

    - name: Install Wrangler
      run: npm install -g wrangler  # Install Wrangler globally using npm

    - name: Publish to Cloudflare Workers
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}  # Use the Cloudflare API token from secrets
      run: wrangler deploy ./my-worker/worker.js  # Deploy the Cloudflare Worker